engines:
  eslint:
    enabled: true
  nodesecurity:
    enabled: false
  csslint:
    enabled: false
    include_paths:
      - public/index.html
  fixme:
    enabled: false
ratings:
  paths:
    - "*.js"
    - "lib/**/*"
    - "public/**/*"
    - "routes/**/*"
    - "test/**/*"
exclude_paths:
  - "node_modules/**/*"
  - "coverage/**/*"
  - ".git/**/*"
